server:
  port: 8886

spring:
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 授权码
    password: llrpbloddmvpdacc
    # 编码格式
    default-encoding: UTF-8
    # 邮箱地址
    username: 3494525791@qq.com
    # 端口
    port: 25

  rabbitmq:
    username: city
    password: spring
    host: 106.54.183.43
    port: 5672