server:
  port: 8888

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      # 最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 10
      # 连接请求超时时间
      max-wait: 1000
      # 测试连接是否可用的查询语句
      # validation-query: SELECT 1

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    username: city
    password: spring
    host: 106.54.183.43
    port: 5672
    # 消息确认回调
    publisher-confirm-type: correlated
    # 消息失败回调
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-prefix: t_

logging:
  level:
    com.city.server.dao.mapper: debug
