server:
  port: 8886

spring:
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 协议
    protocol: smtp
    # 授权码
    # password:
    # 编码格式
    default-encoding: UTF-8
    # 邮箱地址
    # username:
    # 端口
    port: 25

  rabbitmq:
    username: root
    password: root
    host: localhost
    port: 5672